-- Create expenses table
create table expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null default current_date,
  category text not null,
  description text,
  amount decimal(12,2) not null check (amount > 0),
  created_by uuid references auth.users(id)
);

-- Enable RLS
alter table expenses enable row level security;

-- Policies
create policy "Enable read access for all authenticated users" on expenses
  for select using (auth.role() = 'authenticated');

create policy "Enable insert access for all authenticated users" on expenses
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update access for all authenticated users" on expenses
  for update using (auth.role() = 'authenticated');

create policy "Enable delete access for all authenticated users" on expenses
  for delete using (auth.role() = 'authenticated');
